
using System.Windows.Forms;

namespace DebugDesktopManager
{
    // must be first in file for designer to work...
    // must be first in file for designer to work...
    // must be first in file for designer to work...
    // must be first in file for designer to work...
    // must be first in file for designer to work...
    // must be first in file for designer to work...
    // must be first in file for designer to work...
    // must be first in file for designer to work...
    // must be first in file for designer to work...
    // must be first in file for designer to work...
    // must be first in file for designer to work...
    // must be first in file for designer to work...
    // must be first in file for designer to work...
    // must be first in file for designer to work...
    // must be first in file for designer to work...

    public partial class Form1 : Form
    {
        Manager manager;

        public Form1()
        {
            InitializeComponent();

            SuspendLayout();
            manager = new Manager(pictureBox1);
            ResumeLayout();
        }

        ~Form1()
        {
            manager.Dispose();
        }
    }
}
